# NumPy-arrayer

NumPy-pakken kommer med en datatype som heter *ndarray* (kalt "NumPy-array" eller bare "array"), NumPy er bygd rundt denne datatypen. En NumPy-array har mange likheter med den vanlige listen fra Python, men er annerledes på to viktige vis: For det første, kan en NumPy-array kun inneholde elementer av én bestemt datatype, ikke en blanding. For det andre, tillater derfor arrayer regneoperasjoner som gjøres "samtidig" på alle elementene i arrayen

## Lage NumPy-arrayer

Vi kan begynne med å lage en NumPy-array fra en liste eller et tuppel (som kun inneholder elementer av samme datatype!) med *array*-funksjonen fra NumPy. Syntaksen er da *array(liste)*. Det er vanlig kutyme å importere NumPy-pakken under navnet "np".

### Eksempel

In [2]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## Indeksering og slicing

Vi kan indeksere og slice arrayer på samme måte som lister og tupler. Vi kan også slice slik at vi hopper over elementer med syntaksen *array[start, slutt, steg]*, der *steg* er et heltall som bestemmer med hvilket mellomrom vi tar med indekser i slicen, der 1 er hver, 2 er annenhver, 3 er hver tredje og så videre. (Dette fungerer også for lister og tupler!)

### Eksempel

In [1]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr[2])     # Indeksering
print(arr[2:])    # Slice fra og med indeks 2
print(arr[2::2])  # Slice med annenhvert element fra og med indeks 2

3
[3 4 5]
[3 5]


## linspace og arange

Vi får ofte bruk for arrayer bestående av tall med jevne mellomrom. NumPy-funksjonene *linspace* og *arange* gjør det enkelt å lage slike arrayer. Med *linspace* kan vi lage en array med *n* elementer mellom to punkter *start* og *stopp* med funksjonskallet *linspace(start, stopp, n)*. Med *arange* kan vi lage en array med elementer med et fast mellomrom *steg* mellom to punkter med *arange(start, stop, steg)*.

### Eksempel

In [ ]:
import numpy as np

arr1 = np.linspace(-10, 10, 5)
arr2 = np.arange(-5, 5, 1)

print(arr1)
print(arr2)  # arange teller til, men ikke med, sluttpunktet 5

[-10.  -5.   0.   5.  10.]
[-5 -4 -3 -2 -1  0  1  2  3  4]


## Regneoperasjoner med arrayer

Den store fordelen med arrayer er at vi kan gjøre matematiske regneoperasjoner på dem direkte. Vi kan utføre de vanlige aritmetikkoperasjonene fra Python (+, -, *, /, **) på to arrayer (dersom de er like lange!) Når vi gjør dette blir regneoperasjonen utført *elementvis*, altså blir for eksempel *([a, b, ...]) + ([[A, B, ...]]) = ([a+A, b+B, ...])* (her brukes skrivemåten *([...])* til å symbolisere en array).

### Eksempel

In [ ]:
import numpy as np

liste1,liste2 = [1,2],[3,4]
arr1,arr2 = np.array(liste1),np.array(liste2)

print(liste1+liste2)  # + for lister tilsvarer konkatenering
print(arr1+arr2)        # + for arrayer tilsvarer elementvis addisjon

[1, 2, 3, 4]
[4 6]


Vi kan også utføre regneoperasjoner mellom tall og arrayer, som tolkes som å gjøre operasjonen elementvis. Det vil si at for eksempel *n+([a,b, ...]) = ([n+a, n+b, ...])*.

### Eksempel

In [ ]:
arr = np.array([1,2,3,4])

print(2*arr)

[2 4 6 8]


NumPy-funksjoner fungerer på samme vis; de utføres elementvis. Altså er *np.funksjon([a,b, ...]) = ([np.funksjon(a), np.funksjon(b), ...])*.

### Eksempel

In [ ]:
import numpy as np
from numpy import pi

arr = np.array([0,pi/2,pi,3*pi/2,2*pi])
arr2 = np.cos(arr)

print(arr2)
print(np.round(arr2))  # np.round runder av til nærmeste heltall, eller til en gitt desimalplass hvis man oppgir det

[ 1.0000000e+00  6.1232340e-17 -1.0000000e+00 -1.8369702e-16
  1.0000000e+00]
[ 1.  0. -1. -0.  1.]
